apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cmp
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - storage/sqlite-pvc.yaml
  - storage/keycloak-pvc.yaml
  - keycloak/realm-configmap.yaml
  - keycloak/service.yaml
  - keycloak/statefulset.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ingress/ingress.yaml
  - cronjobs/db-backup.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - ingress/cluster-issuer.yaml
