apiVersion: v1
kind: Secret
metadata:
  name: cmp-backend-secrets
  namespace: cmp
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: "%9t%$bsEGhZ2NMb66Xa2VgAg"
  JWT_SECRET: "n$M$8QM*SmNH3U6Uc%UL3tzZ5P57n%yn"
  SMTP_USER: "SMPT"
  SMTP_PASS: "!n$2eM8bj$2BcS1nzmyatWw*"
---
apiVersion: v1
kind: Secret
metadata:
  name: cmp-keycloak-admin
  namespace: cmp
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "#7U9qMS^F%PZzD!2nWcHT5k7^"
