apiVersion: v1
kind: Service
metadata:
  name: cmp-keycloak
  namespace: cmp
spec:
  selector:
    app: cmp-keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
